name: Flask Tests
on:
  push: # Correct indentation here
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate # Linux/macOS
          pip install -r requirements.txt
      - name: Set up Database
        run: |
          source venv/bin/activate
          python run.py # Initialize DB
      - name: Run Tests
        run: |
          source venv/bin/activate
          python -m unittest discover -v
